/*
 * This source file was generated by the Gradle 'init' task
 */
package limelight;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        LimelightSimulator classUnderTest = new LimelightSimulator();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}